appname: test
traces: 1
charset: 'UTF8'
content_type: "text/plain"
logger: "console"
template: "template_toolkit"

session: 'YAML'

engines:
  template:
    template_toolkit:
      encoding: 'utf-8'
  serializer:
    json:
      pretty: 1

plugins:
  Foo:
    stuff: 42
